adobe/helix-project-boilerplate

- README.md
Small README improvements for the curios trying to set this up
> chore: improve README.md with setup instructions

- scripts/scripts.js
Fix #24 
Will need some extra love in the future to reduce to the bare minimum, organise the source code better (group functions better) and document extension points. But slowly progressing!
> feat: align loading sequence to latest "standard"

- blocks/example/example.css
- blocks/hero/hero.css
- scripts/scripts.js
- styles/styles.css
https://default-styling--helix-pages-starter--adobe.hlx3.page/
vs.
https://main--helix-pages-starter--adobe.hlx3.page/
> feat: add ootb box styling

- blocks/footer/footer.js
- blocks/header/header.js
- scripts/scripts.js
- test/blocks/footer/footer.plain.html
- test/blocks/footer/footer.test.js
- test/blocks/header/header.test.js
- test/blocks/header/nav.plain.html
- test/scripts/body.html
Test header and footer
https://header-test--helix-project-boilerplate--adobe.hlx3.page/
> test: header and footer

- blocks/example/example.css
- blocks/example/example.js
- blocks/header/header.css
- scripts/scripts.js
- styles/styles.css
- test/blocks/example/example.test.js
- removed `$` notation in variable names
- linted weird spacing in css
> let's do that separately... it is used in a lot of places...
_Originally posted by @davidnuescheler in https://github.com/adobe/helix-project-boilerplate/pull/55#discussion_r797911046_
https://lint--helix-project-boilerplate--adobe.hlx.live/
> fix: remove $, fix css spacing

- scripts/scripts.js
https://relative-links--helix-project-boilerplate--adobe.hlx.live/
> feat: make links relative

- blocks/footer/footer.css
- blocks/header/header.css
- scripts/scripts.js
- styles/styles.css
https://section-meta--helix-project-boilerplate--adobe.hlx3.page/
vs. 
https://main--helix-project-boilerplate--adobe.hlx3.page/
introducing section metadata
> feat: section metadata

- .github/pull_request_template.md
- README.md
- scripts/scripts.js
- test/blocks/header/nav.plain.html
Test URL: https://hlx3-hlx--helix-project-boilerplate--adobe.hlx3.page/?rum=on
> chore: rename hlx3 to hlx

- scripts/scripts.js
https://theme-and-template--helix-project-boilerplate--adobe.hlx.page/
> feat: add theme and template

- scripts/scripts.js
https://placeholders--helix-project-boilerplate--adobe.hlx.page/
> feat: placeholders

- blocks/footer/footer.js
- blocks/header/header.js
- scripts/scripts.js
this is a client sided implementation of https://github.com/adobe/helix-pipeline-service/issues/386
to see if it is feasible.
https://icon-handling--helix-project-boilerplate--adobe.hlx.page/
as there are currently no icons in the project there is not much to see here.
> Icon handling

- scripts/scripts.js
- styles/styles.css
vs.
https://buttons--helix-project-boilerplate--adobe.hlx.page/
scroll down to see the buttons...
> feat: intial buttons

- blocks/header/header.css
- scripts/scripts.js
- styles/styles.css
https://nav-height--helix-project-boilerplate--adobe.hlx.page/#headline-here
vs.
https://main--helix-project-boilerplate--adobe.hlx.page/#headline-here
introducing a `nav-height` variable and removing some extraneous pieces from `styles.css`
> chore: nav height and styles cleanup

- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/footer/footer.css
- blocks/hero/hero.css
- styles/styles.css
https://cards--helix-project-boilerplate--adobe.hlx.live/drafts/uncled/
> feat: cards

- 404.html
add sample 404 page
- ~~attempting to balance simplicity with visual interest (my hope is that the "0" is somewhat reminiscent of a faulty helix strand)~~
- a "go back" button will be added in addition to the "go home" button if there is a `document.referrer` and its origin matches the `window.location`'s origin
Fix #63 
Test URLs:
- Before: https://main--helix-project-boilerplate--adobe.hlx.page/error
- After: https://404--helix-project-boilerplate--adobe.hlx.page/error
> feat: custom 404 example

- scripts/scripts.js
URL for testing:
- https://rum-without-timeouts--helix-project-boilerplate--adobe.hlx.page/?rum=on
> fix(rum): do not rely on timeouts, instead start rum observation after `lazy` checkpoint has passed

- scripts/scripts.js
Test URLs:
- After: https://to-classname--helix-project-boilerplate--adobe.hlx.page/
thanks to [@mengtian1015](https://github.com/mengtian1015)
> feat: improved toClassName

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/add-patch.sh
- README.md
This PR adds a GitHub Codespaces configuration that pre-installs the Franklin CLI and updates the Readme with usage instructions.
> Enable GitHub Codespaces

- README.md
Let's add that letter to make it easier to read
changed: https://github.com/adobe/helix-project-boilerplate/blob/84b4495f0920f2c9464ea2a0562e8ba8b1a8ae29/README.md
> chore: Update README.md: npm test

- blocks/columns/columns.css
- blocks/columns/columns.js
when a column in the columns block is an image-only column, it will display before (or above) other column row content.
Test URLs:
- After: https://columns--helix-project-boilerplate--adobe.hlx.page/
> feat: image-only columns will display first on mobile view

- scripts/lib-franklin.js
Fix #222
Test URLs:
- After: https://222-display-none--helix-project-boilerplate--synox.hlx.page/
> chore: fix #222 remove duplicate body: display:none
