adobe/helix-project-boilerplate

test/unit/blocks/blocks.test.js
For more realistic test output (buttons, icons etc), block tests should always run `decorateMain()` first.
=> test: run decorateMain

scripts/scripts.js
I think we should drop empty sections (e.g. left over from a metadata block) to avoid unexpected spacing from margins or paddings.
=> feat: drop instead of wrap empty sections

.github/workflows/run-tests-on-fork.yaml
separate jobs for PRs from forks to avoid duplicate runs for "domestic" PRs.
=> feat: also run test for PRs from forks

scripts/scripts.js
https://no-blocks--helix-project-boilerplate--adobe.hlx3.page/default-content-examples
vs. 
https://main--helix-project-boilerplate--adobe.hlx3.page/default-content-examples
=> fix: update section status if page has no block

scripts/scripts.js, styles/styles.css, test/blocks/example/block.html, test/scripts/scripts.test.js
https://block-wrapper--helix-project-boilerplate--adobe.hlx3.page/
vs.
https://main--helix-project-boilerplate--adobe.hlx3.page/
i think we often run into the situation, where a block requires a different `max-width` or `background` from the default content or other blocks.
in the past, i usually split them off into different sections to achieve that, which i realized recently is not the best solution as it removes the information about the section boundary.
i noticed that we had a concept that we had in the existing DOM that could help with that. 
in the current main branch we have a DOM that looks as follows...
there is a somewhat underutilized `<div>` below the `.section-wrapper` that we usually use for the `max-width` of default content and blocks in a section.
if we break this up and …
=> feat: block-wrapper

scripts/scripts.js
https://safari-img-loading--helix-project-boilerplate--adobe.hlx.live/
vs. 
safari (surprisingly, at least to me) still doesn't support `loading="lazy"` and as a side effect of that feels compelled to load every `img` element (even if it is not attached to the DOM yet) as soon as the `src` attribute is set, which means that the fallback `jpg`/`png` images are always loaded. setting the `src` attribute after attaching the `img` element to containing `picture` element seems to fix that.
=> chore: safari img loading suppression

scripts/scripts.js
https://eager-lcp--helix-project-boilerplate--adobe.hlx.live/
vs. 
there are circumstances where the lcp (eg. if it is calculated or selected by an lcp block) ends up being an image that's loaded `lazy`, which will hang the lcp promise because the containing section will still be hidden.
there is really no good reason for something that we identify as the lcpCandidate to ever not be `eager` loaded, so setting the `loading` in the block loader makes it a little bit less error prone for the block developer.
=> feat: protect against lazy lcp candidates

blocks/example/example.css, blocks/footer/footer.css, blocks/header/header.css, styles/styles.css
https://unclever--helix-project-boilerplate--adobe.hlx3.page/
vs.
https://main--helix-project-boilerplate--adobe.hlx3.page/
there were a number of clever aspects of the design that don't map to what's typically encountered in projects (eg. font sizes in `rem` and `%` or colors as decimal rgb values) so this PR removes all of that and replaces it with a more typical scenario encountered in projects.
=> chore: remove smart sizing and colors

.hlxignore
not sure why we excluded all `.json`, maybe because of the `.json`s in the root?
=> chore: add json to codebus

helix-query.yaml
Description property is listed twice to helix-query.yaml.
=> fix: description added twice to index

404.html
This is an extension of #99 and adds some RUM instrumentation to the error page, so that we can later on generate reports on pages that are missing and pages that have likely broken links.
checkpoint is `404` (not `error`, so that we can distinguish it from a JS error). `source` is the referrer and `target` the current URL
Test URLs:
- Before: https://404--helix-project-boilerplate--adobe.hlx.page/error?rum=on
- After: https://404-rum--helix-project-boilerplate--adobe.hlx.page/error?rum=on
=> feat(404): add rum instrumentation

scripts/scripts.js
while adding image support to `readBlockConfig` i also realized that there was a bug using kebob-case instead of camelCase for the dataset name...
compare:
https://block-config-img-support--helix-project-boilerplate--adobe.hlx.page/drafts/uncled/
vs.
https://main--helix-project-boilerplate--adobe.hlx.page/drafts/uncled/
to see the changes beyond the obvious fix, you have to inspect the attributes of the highlighted section.
=> block config img support

styles/styles.css
vs.
https://heading-font--helix-project-boilerplate--adobe.hlx.page/
=> chore: use heading font

scripts/scripts.js
- adding missing rum addition sourceselector
- adding missing rum addition targetselector
- adding missing rum addition observe
- adding observe invocations
- adding missing rum addition mediaobserver
- adding missing rum addition blockobserver
- adding event listener for error
- adding event listener for unhandledrejection
Test URLs
- before: https://main--helix-project-boilerplate--adobe.hlx.page/?rum=on
- after:  https://advancedrum--helix-project-boilerplate--adobe.hlx.page/?rum=on
Edits performed by https://github.com/trieloff/helix-codemods/blob/main/transforms/advancedrum.js
=> feat(rum): add advanced rum tracking

blocks/header/header.css
Test URLs:
- After: https://nav-brand-img-height--helix-project-boilerplate--adobe.hlx.page/
See https://main--gscouts--hlxsites.hlx.page/index1 an example of the problem:
=> fix: nav brand img height

scripts/scripts.js
https://main--helix-project-boilerplate--adobe.hlx.page/drafts/uncled/multiple-classes
vs.
https://allow-multiple-classes--helix-project-boilerplate--adobe.hlx.page/drafts/uncled/multiple-classes
=> fix: allow multiple classes on theme, template and style

styles/styles.css
This fix is just cosmetic and won't change the look & feel of buttons, as the fallback for the missing variable will be the body's font family.
https://btn-font--helix-project-boilerplate--adobe.hlx.page/
=> fix(button): font-family variable

scripts/scripts.js
Once read, the section metadata block is removed. But its wrapper remains as an empty div in the dom which might cause issues for styling.
Before: https://main--helix-project-boilerplate--adobe.hlx.page/
After: https://section-metadata-empty-div--helix-project-boilerplate--adobe.hlx.page/
=> fix: section metadata leaves an empty div

404.html
https://main--helix-project-boilerplate--adobe.hlx.live/404.html
vs.
https://lib-helix--helix-project-boilerplate--adobe.hlx.live/404.html
=> Fixed sampleRUM import

scripts/scripts.js
vs.
https://add-lang--helix-project-boilerplate--adobe.hlx.live/
=> chore: add lang

scripts/lib-franklin.js
Test URLs:
- Before: https://main--helix-project-boilerplate--adobe.hlx.page/?rum=on
- After: https://no-double-top--helix-project-boilerplate--adobe.hlx.page/?rum=on
In the before setup, the `top` checkpoint would be sent twice, once from `top` and once from `lazy`
Before:
1. `top`
2. `load`
3. `lazy`
4. `top` (again?)
5. favicon
After:
1. `top`
2. `load`
3. `lazy`
4. favicon
5. `viewmedia`
=> fix(rum): do not send `top` checkpoint twice

.gitignore, scripts/lib-franklin.js, test/scripts/scripts.test.js, test/scripts/types.d.ts
fixes the scripts tests by adding an exported `setup` function to lib and setting `window.hlx.lighthouse`
Test URLs:
- Before: https://main--helix-project-boilerplate--adobe.hlx.page
- After: https://fix-tests--helix-project-boilerplate--adobe.hlx.page
=> chore: fix tests

scripts/scripts.js
Fix #167 
Test URLs:
- Before: 
https://main--helix-project-boilerplate--adobe.hlx.page/#
https://main--helix-project-boilerplate--adobe.hlx.page/#valid
https://main--helix-project-boilerplate--adobe.hlx.page/#old_hash=&from_ims=true
- After:
https://gh167-scroll-into-view-fix--helix-project-boilerplate--adobe.hlx.page/
https://gh167-scroll-into-view-fix--helix-project-boilerplate--adobe.hlx.page/#
https://gh167-scroll-into-view-fix--helix-project-boilerplate--adobe.hlx.page/#valid
https://gh167-scroll-into-view-fix--helix-project-boilerplate--adobe.hlx.page/#old_hash=&from_ims=true
=> fix: handle invalid hashes without throwing error

blocks/header/header.css, blocks/header/header.js, test/blocks/header/header.test.js
couple of ideas for the nav
https://nav-touchups--helix-project-boilerplate--adobe.hlx.live/
vs.
(1) introducing nav wrapper:
(2) minor naming proposal:
`MQ` seems a bit generic, i think semantically it would be `isDesktop`
(3) nav config via meta:
somehow we seem to have used block config to specify the nav path, but i don't think that's practical way of doing it, i would propose to use meta instead
(4) bumping z-index:
i think hero (and any other background image situation) should use `z-index` `0` and `1` instead of the current `-1` setup, since that one is not compatible with simple background colors.
=> Minor Nav touch-up ideas

blocks/footer/footer.js, blocks/header/header.js
there are some repeated questions related to browser cache after publishing changes to `nav` or `footer`.
here is some simple logic that forces a `reload` of the `.plain.html`
https://main--helix-project-boilerplate--adobe.hlx.live/nav
vs.
https://nav-reload--helix-project-boilerplate--adobe.hlx.live/nav
=> chore: better nav reload after publish

package.json
when running CSS linting, i get the following error:
```
$ npm run lint:css
> @adobe/helix-project-boilerplate@1.0.0 lint:css
> stylelint 'blocks/**/*.css' 'styles/*.css'
Error: No files matching the pattern "'blocks/**/*.css', 'styles/*.css'" were found.
at standalone (D:\Develop\github\adobe\helix-project-boilerplate\node_modules\stylelint\lib\standalone.js:260:43)
```
Tested in Environment: Windows with Powershell and Git Bash
https://feature-fix-css-linting--helix-project-boilerplate--stefanseifert.hlx.page/
=> Fix CSS linting arguments

scripts/lib-franklin.js
https://github.com/adobe/helix-project-boilerplate/commit/b478ec34a5d283f475146ad895178f682844e65d introduced an optimized way to handle displaying icons based on SVG sprited. unfortunately the code seems to be broken and icons are mis-referenced in the sprite. (the commit did not contain unit tests, nor was there content to visualize it.)
this PR should fix the problem.
Test URLs:
- Before: https://main--helix-project-boilerplate--adobe.hlx.live/
- After: https://feature-svg-sprite--helix-project-boilerplate--stefanseifert.hlx.live/
=> Fix display of icons from SVG sprite

styles/styles.css
we have some CLS protection in styles.css that are a part of lib-franklin and not part of the project.
to separate concerns a little better, i am proposing to move those directly into lib-franklin i think there is a possibly for a FOUC but i would say that possibility has existed before, and some PSI testing may shed some light...
https://cls-to-script--helix-project-boilerplate--adobe.hlx.page/
vs.
=> chore: remove extra css for cls protection to script

scripts/lib-franklin.js, test/scripts/body.html
to be consistent with our best practices we should move the picture breakpoint to `600px`
vs.
https://better-picture-breakpoint--helix-project-boilerplate--adobe.hlx.live/
=> chore: better image breakpoint

scripts/scripts.js, styles/styles.css
it looks like the script only solution produces a `FOUC` on certain devices... moving back the `body.appear` based protection for the time being.
vs.
https://cls-to-script--helix-project-boilerplate--adobe.hlx.live/
before:
after:
=> chore: re-add body hiding to css

scripts/lib-franklin.js
BREAKING CHANGE: the default behavior of RUM collection is now to omit URL parameters. To restore the old behavior set `window.hlx.RUM_MASK_URL = 'full'`
- After: https://trieloff-patch-2--helix-project-boilerplate--adobe.hlx.page/?rum=on
=> fix(rum): do not submit URL parameters to RUM collection

.github/workflows/run-tests.yaml
Use npm 8 or later for the builds by using node 16
Fix #198
URL for testing:
- https://patch-1--helix-project-boilerplate--phi-x-174.hlx.page/
=> Use npm 8 or later to avoid build failures due to package lock versions

scripts/lib-franklin.js
this is an attempt to modernize `loadCSS()` and add `loadScript()`
for loadCSS this is a breaking change, input is very welcome...
i lifted a lot of the `loadScript()` code from @synox 
https://load-css-script--helix-project-boilerplate--adobe.hlx.live/
vs.
=> chore: refactor loadCSS, add loadScript

blocks/cards/cards.js
replacing the `.innerHTML` is incompatible with the block loader as it removes the elements that were referenced as blocks. this becomes particularly visible during autoblocking eg. fragments.
https://fragment-compatible-cards--helix-project-boilerplate--adobe.hlx.page/
vs.
=> chore: fix cards to be autoblocking / fragment compatible

scripts/lib-franklin.js
Enables listeners to all RUM events, not just the sampled ones.
Using RUM for instrumentation and forwarding the RUM events of interest to WebSDK client-side depends on this feature being present in the boilerplate code.
Same is applicable for conversion tracking using RUM https://github.com/adobe/franklin-rum-conversion/tree/main and then forwarding the conversion events to Analytics via WebSDK.
Code changes could not be extracted to an isolated library/file as the logic resides in the sampleRUM method and there is no extension point available atm.
Already used for:
- BambooHR: https://github.com/BambooHR/bamboohr-website/blob/main/scripts/scripts.js#L158-L160
- WKND: https://github.com/hlxsites/wknd/pull/22/files#diff-a5ee87ff9063f921ba01933977e6164e5729551986030f0ed7eb747bcffb740fR73 …
=> feat: enable listeners to all RUM events, not just the sampled ones

.gitignore, scripts/lib-franklin.js
Fix https://github.com/adobe/helix-project-boilerplate/pull/247 where the `sampleRUM.always[checkpoint]` is still called inside the if for RUM selected events
Test URLs:
- Before: https://main--helix-project-boilerplate--iuliag.hlx.page/
- After: https://fix-samplerum-always--helix-project-boilerplate--iuliag.hlx.page/
=> fix: sampleRUM always for checkpoint to be called even if RUM not selected

scripts/lib-franklin.js
We've had several cases in the past where we needed to override the default block config logic when loading blocks:
- experimentations may load from a different folder name, or load a different js/css file in the same block folder
- themes that were loading alternate CSS files for block variants
To make maintaining those downstream projects easier, I propose to directly add an extension mechanism so we have fewer modifications to the `lib-franklin.js` file.
Test URLs:
- After:
- https://extend-block-config--helix-project-boilerplate--ramboz.hlx.page/ (regular page not using the extension mechanism)
- https://main--franklin-experience-decisioning--ramboz.hlx.page/experiments/control (page with experimentation using the …
=> feat: add capability to patch block config at runtime

styles/styles.css
`unset` on `<body>` seems to result in `inline` which is a bit unexpected for `<body>` and may yield side-effects.
vs.
https://body-block--helix-project-boilerplate--adobe.hlx.live/
=> chore: change display to block instead of unset
